<?php

namespace AppBundle\Repository;

/**
 * skladisteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class skladisteRepository extends \Doctrine\ORM\EntityRepository
{
}
